name: vagabond
channels:
  - conda-forge
dependencies:
  - xeus-cling=0.8.1
  - xtensor=0.21.2
  - xtensor-blas=0.17.1
  - scijava-jupyter-kernel
  - sos-notebook
  - javascripthon
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - notebook